---
############################# INSTALL JQ ################################
- name: armv6l | install jq /1
  command: cp {{ blobs }}/jq-rpi /usr/local/bin/jq
      creates=/usr/local/bin/jq
  # Note: this will not update jq if changed
  sudo_user: root
- name: armv6l | install jq /2
  file: path=/usr/local/bin/jq owner=root group=root mode=0755
  sudo_user: root

############################# SETUP WIFI ################################
- name: armv6l | create /etc/wpa_supplicant/
  file: path=/etc/wpa_supplicant/ state=directory
  sudo_user: root
- name: armv6l | store old wpa_supplicant.conf md5
  stat: path=/etc/wpa_supplicant/wpa_supplicant.conf
  register: wpa_conf_old
  sudo_user: root
- name: armv6l | populate /etc/wpa_supplicant/wpa_supplicant.conf
  script: wpa_supplicant-conf.py {{ home }} {{ config }}/config
  sudo_user: root
- name: armv6l | get new wpa_supplicant.conf md5
  stat: path=/etc/wpa_supplicant/wpa_supplicant.conf
  register: wpa_conf_new
  sudo_user: root
- name: armv6l | ifdown/ifup wlan0
  shell: ifdown wlan0; sleep 1; ifup wlan0
  sudo_user: root
  when: wpa_conf_old.stat.md5 is undefined or wpa_conf_old.stat.md5 != wpa_conf_new.stat.md5

############################# SETUP SNTP ################################
- name: armv6l | disable ntpd
  service: name=ntp state=stopped enabled=no
  sudo_user: root

- name: armv6l | install the sntp script
  copy: src=sntp dest=/etc/init.d/sntp
      owner=root group=root mode=0755
  sudo_user: root
- name: armv6l | enable sntp
  service: name=sntp enabled=yes
  sudo_user: root

################################# MISC ##################################
- name: armv6l | setup and mount tmpfs
  mount: name={{ home }}/smarthome src=tmpfs fstype=tmpfs
      state=mounted
  sudo_user: root

- name: armv6l | remove swapfile
  command: dphys-swapfile uninstall
  sudo_user: root
- name: armv6l | disable swap
  service: name=dphys-swapfile enabled=no
  sudo_user: root
