#!/bin/bash

### BEGIN INIT INFO
# Provides:        mkdirs
# Required-Start:  $remote_fs
# Required-Stop:   $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Ensure that folders exist
### END INIT INFO

case $1 in
    start)
    {% for dir in folders.stdout_lines %}
        sudo -u smarthome mkdir -p "{{ dir| replace("~", home) }}"
    {% endfor %}
        ;;
    *)
        echo "Usage: $0 start"
        ;;
esac
