#!/bin/bash

### BEGIN INIT INFO
# Provides:        sntp
# Required-Start:  $network $remote_fs
# Required-Stop:   $network $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Run SNTP
### END INIT INFO

case $1 in
    start)
        until sntp -s 1.pool.ntp.org
        do sleep 2; done
        ;;
    *)
        echo "Usage: $0 start"
        ;;
esac
